---
- name: Deploy App in Minikube
  hosts: minikube

  tasks:
    - name: Copy manifest.yaml
      copy:
        src: /home/ansibleadmin/your_directory/manifest.yaml
        dest: /home/muser/manifest.yaml
  
    - name: Deploy ressources.yaml
      command: "kubectl apply -f /home/muser/manifest.yaml"
      become: yes
      become_user: muser
